name: Build Loader Template

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Debug structure
        run: |
          pwd
          ls -la
          ls -la loader || true

      - name: Make gradlew executable
        run: chmod +x ./loader/gradlew

      - name: Build loader
        run: ./loader/gradlew build

      - name: Upload loader-template.jar
        uses: actions/upload-artifact@v4
        with:
          name: loader-template
          path: loader/build/libs/loader-template.jar
